// Each #kernel tells which function to compile; you can have many kernels
#define GROUP_SIZE 128
#pragma kernel LeanGrass

struct GrassClump
{
    float3 position;
    float lean;
    float noise;
};

RWStructuredBuffer<GrassClump> clumps;
float time;
float maxLean;

[numthreads(GROUP_SIZE, 1, 1)]
void LeanGrass(uint3 id : SV_DispatchThreadID)
{
    GrassClump clump = clumps[id.x];
    clump.lean = max(sin(time) * maxLean * clump.noise, maxLean);
    clumps[id.x] = clump;
}
