// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Highlight

Texture2D<float4> source;
RWTexture2D<float4> output;
float radius;
float edge;
float shade;
float4 center;

float circle(const float2 pos, const float2 center, const float radius, const float edge)
{
    const float len = length(pos - center);
    return 1 - smoothstep(radius - edge, radius, len);
}

[numthreads(8, 8, 1)]
void Highlight(uint3 id : SV_DispatchThreadID)
{
    const float inCircle = circle(id.xy, center.xy, radius, edge);
    const float effectiveShade = lerp(shade, 1, inCircle);
    output[id.xy] = source[id.xy] * effectiveShade;
}