// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> result;
int textureResolution;
float time;

float random(const float2 pos, const float seed)
{
    const float2 n = float2(12.9898, 78.233);
    const float c = 43758.543123;
    return frac(sin(dot(pos, n) + seed) * c);
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    const float4 white = 1;
    const float2 position = id.xy / (float)textureResolution;
    result[id.xy] = random(position, time) * white;
}
